### PR TITLE
Added a SiteimproveAdmins role to authorize attribute in controllers

### PR DESCRIPTION
**Pull request by kwillumsen**
Need to give access to Siteimprove overlay in Epi CMS edit mode for user not in Administrators, WebAdmins, CmsAdmins. Added new role SiteimproveAdmins for this

### CODE REVIEW

**Comment by CasperTDK** [comment]
Should it not be CmsEditors instead?

**Comment by kwillumsen** [comment]
Could be if the purpose of the module is to give access to editors as well. I just followed your "Admin" roles setup :) 
Maybe the Roles in Authorize attribute for SiteimproveController and SiteimproveAdminController should differ. "Editors" roles in SiteimproveController and "Admins" roles in SiteimproveAdminController 

Our customer have users (Uses windowsmembership and role provider) that isn't in an admin role and shouldn't be but still needs to have access to the module. 
For that purpose we need that extra role added so we can do this in 
```
<episerver.framework><virtualRoles><providers>

<add name="SiteimproveAdmins" roles="domain\rolename" mode="Any" type="EPiServer.Security.MappedRole, EPiServer" />
```

**Comment by CasperTDK** [comment]
Alright. That makes sense. I will review and merge the ticket!

**Comment by CasperTDK** [comment]
I've pushed the package to episerver, pending their nuget approval - it can take a few days

**Comment by kwillumsen** [comment]
Great thanks

**Comment by CasperTDK** [comment]
Hi @kwillumsen It is out:
http://nuget.episerver.com/en/OtherPages/Package/?packageId=SiteImprove.EPiServer.Plugin

**Pull request merged**
